version: "3.6"

services:
  redis:
    image: redis:5-alpine
    container_name: redis
    tmpfs:
       - /data
    volumes:
      - ./redis.conf:/redis.conf
    ports:
      - "6379:6379"
    command: ["/redis.conf"]

  mongodb:
    image: mongo:4
    container_name: mongodb
    tmpfs:
      - /data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      discovery.type: single-node
    container_name: elasticsearch
    tmpfs:
      - /usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
